accounts/urls.py
#urls for accounts app
from django.urls import path
# urls for auth views
from django.contrib.auth import views as auth_views
#viwews for accounts app
from . import views

app_name = 'accounts'
# URL patterns for the accounts app
urlpatterns = [
    path(
        'login/', 
        auth_views.LoginView.as_view(template_name='accounts/login.html'), 
        name='login'
    ),
    path(
        'logout/', 
        auth_views.LogoutView.as_view(), 
         name='logout'
         ),
    path(
        'logout_message/',
        views. LogoutMessageView.as_view(),
        name='logout_message'
    ),
    path(
        'signup/', 
         views.SignUpView.as_view(), 
         name='signup'
         ),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('persona/', include('persona.urls')),
    path('oficina/', include('oficina.urls')),
    path('accounts/', include('accounts.urls')),
    path('captcha/', include('captcha.urls')),
   
]

oficina/urls.py
from django.urls import path
from .views import *


app_name = 'oficina'

urlpatterns = [
    path('lista/', 
         OficinaListView.as_view(), 
         name='lista'),
    path('buscar/', 
         OficinaSearchView.as_view(), 
         name='buscar'),
    path('detalle/<int:pk>/', 
         OficinaDetailView.as_view(), 
         name='detalle'),
    path('empleados/<int:pk>/', 
         OficinaEmpleadoListView.as_view(), 
         name='empleados'), 
    path('crear/', 
         OficinaCreateView.as_view(), 
         name='crear'),
    path('editar/<int:pk>/', 
         OficinaUpdateView.as_view(), 
         name='editar'),
    path('eliminar/<int:pk>/', 
         OficinaDeleteView.as_view(), 
         name='eliminar'),
]

persona/urls.py
from django.urls import path
from .views import *

app_name = 'persona'

urlpatterns = [
    path(
        'lista/',
        PersonaListView.as_view(),
        name='lista'
    ),
    path(
        'buscar/',
        PersonaSearchView.as_view(),
        name='buscar'
    ),
    path(
        'detalle/<int:pk>/',
        PersonaDetailView.as_view(),
        name='detalle'
    ),
    path(
        'crear/',
        PersonaCreateView.as_view(),
        name='crear'
    ),
    path(
        'editar/<int:pk>/',
        PersonaUpdateView.as_view(),
        name='editar'
    ),
    path(
        'eliminar/<int:pk>/',
        PersonaDeleteView.as_view(),
        name='eliminar'
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" defer></script>
    <title>CRUD</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'persona:lista' %}">Barra de Navegacion</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link " href="{% url 'persona:lista' %}">Lista de Personas</a>
        </li>
        <li class="nav-item">  
            <a class="nav-link " href="{% url 'oficina:lista' %}">Lista de Oficinas</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Menu
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'persona:crear' %}">Nueva Persona</a></li>
            <li><a class="dropdown-item" href="{% url 'oficina:crear' %}">Nueva Oficina</a></li>
            <li><hr class="dropdown-divider"></li>
          
          </ul>
        </li>
        
      </ul>
      {% if search_action %}
      <form class="d-flex" role="search" action="{% url search_action %}">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search"name="q">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
      <div class="d-flex">
        {% if user.is_authenticated %}
          <span class="navbar-text me-3">Hola, {{ user.username }}</span>
          <a class="btn btn-outline-success" href="{% url 'accounts:logout_message' %}">Salir</a>
        {% else %}
          <a class="btn btn-outline-success me-2" href="{% url 'accounts:login' %}">Ingresar</a>
          <a class="btn btn-outline-success" href="{% url 'accounts:signup' %}">Registrarse</a>
        {% endif %}
      {% endif %}
    </div>
  </div>
</nav>

templates/paginator.html
<nav>
    <ul class="pagination justify-content-center bg-light p-2 rounded">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    &laquo;Anterior
                </a>
            </li>
        
        {% endif %}
        
        {% for num in page_obj.paginator.page_range %}
            {% if num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                {% if num == page_obj.number %}    
                    <li class="page-item active">
                        <span class="page-link">{{ num }} (Actual)</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    Siguiente &raquo;
                </a>
            </li>
        {% endif %}
    </ul>
</nav>